from Gaudi.Configuration import *
from Configurables import DDPandoraPFANewAlgorithm

def new_pandoraPFA():
    """
    Create a new DDPandoraPFANewAlgorithm instance for Pandora PFA.
    """
    return DDPandoraPFANewAlgorithm(
        "PandoraPFANew",
        CreateGaps = False,
        CurvatureToMomentumFactor =  0.00015,
        D0TrackCut =  200,
        D0UnmatchedVertexTrackCut = 5,
        DigitalMuonHits = 0,
        ECalBarrelNormalVector = [0, 0, 1],
        ECalMipThreshold = 0.5,
        ECalScMipThreshold = 0,
        ECalScToEMGeVCalibration = 1,
        ECalScToHadGeVCalibrationBarrel = 1,
        ECalScToHadGeVCalibrationEndCap = 1,
        ECalScToMipCalibration = 1,
        ECalSiMipThreshold = 0,
        ECalSiToEMGeVCalibration = 1,
        ECalSiToHadGeVCalibrationBarrel = 1,
        ECalSiToHadGeVCalibrationEndCap = 1,
        ECalSiToMipCalibration = 1,
        ECalToEMGeVCalibration = 1.02373335516,
        ECalToHadGeVCalibrationBarrel = 1.24223718397,
        ECalToHadGeVCalibrationEndCap = 1.24223718397,
        ECalToMipCalibration = 181.818,
        EMConstantTerm = 0.01,
        EMStochasticTerm = 0.17,
        FinalEnergyDensityBin = 110.,
        HCalBarrelNormalVector = [0, 0, 1],
        HCalMipThreshold = 0.3,
        HCalToEMGeVCalibration = 1.02373335516,
        HCalToHadGeVCalibration = 1.01799349172,
        HCalToMipCalibration = 40.8163,
        HadConstantTerm = 0.03,
        HadStochasticTerm = 0.6,
        InputEnergyCorrectionPoints = [],
        LayersFromEdgeMaxRearDistance = 250,
        MaxBarrelTrackerInnerRDistance = 200,
        MaxClusterEnergyToApplySoftComp = 2000.,
        MaxHCalHitHadronicEnergy = 1000000,
        MaxTrackHits = 5000,
        MaxTrackSigmaPOverP = 0.15,
        MinBarrelTrackerHitFractionOfExpected = 0,
        MinCleanCorrectedHitEnergy = 0.1,
        MinCleanHitEnergy = 0.5,
        MinCleanHitEnergyFraction = 0.01,
        MinFtdHitsForBarrelTrackerHitFraction = 0,
        MinFtdTrackHits = 0,
        MinMomentumForTrackHitChecks = 0,
        MinTrackECalDistanceFromIp = 0,
        MinTrackHits = 0,
        MuonBarrelBField = -1.34,
        MuonEndCapBField = 0.01,
        MuonHitEnergy = 0.5,
        MuonToMipCalibration = 19607.8,
        NOuterSamplingLayers = 3,
        OutputEnergyCorrectionPoints = [],
        PandoraSettingsXmlFile = "PandoraSettings/PandoraSettingsDefault.xml",
        ReachesECalBarrelTrackerOuterDistance = -100,
        ReachesECalBarrelTrackerZMaxDistance = -50,
        ReachesECalFtdZMaxDistance = 1,
        ReachesECalMinFtdLayer = 0,
        ReachesECalNBarrelTrackerHits = 0,
        ReachesECalNFtdHits = 0,
        ShouldFormTrackRelationships = 1,
        SoftwareCompensationEnergyDensityBins = [0, 2., 5., 7.5, 9.5, 13., 16., 20., 23.5, 28., 33., 40., 50., 75., 100.],
        SoftwareCompensationWeights = [1.61741, -0.00444385, 2.29683e-05, -0.0731236, -0.00157099, -7.09546e-07, 0.868443, 1.0561, -0.0238574],
        StartVertexAlgorithmName = "PandoraPFANew",
        StripSplittingOn = 0,
        TrackCreatorName = "DDTrackCreatorCLIC",
        TrackStateTolerance = 0,
        TrackSystemName = "DDKalTest",
        UnmatchedVertexTrackMaxEnergy = 5,
        UseEcalScLayers = [0],
        UseEcalSiLayers = [0],
        UseNonVertexTracks = 1,
        #UseOldTrackStateCalculation = 0,
        UseUnmatchedNonVertexTracks = 0,
        UseUnmatchedVertexTracks = 1,
        YokeBarrelNormalVector = [0, 0, 1],
        Z0TrackCut = 200,
        Z0UnmatchedVertexTrackCut = 5,
        ZCutForNonVertexTracks = 250,
        ClusterCollectionName = ["PandoraClusters"],
        ProngVertexCollections = [],#"ProngVertices"],
        SplitVertexCollections = [],#"SplitVertices"],
        KinkVertexCollections = [],#"KinkVertices"],
        V0VertexCollections = [],#"V0Vertices"],
        TrackCollections = ["SiTracks"],
        RelTrackCollections = ["MergedTrackerHitsRelations"],
        MCParticleCollections = ["MCParticles"],
        MuonCaloHitCollections = ["MuonBarrelHitsKilled", "MuonEndcapHitsKilled"],
        ECalCaloHitCollections = ["EcalBarrelCollectionRecKilled", "EcalEndcapCollectionRecKilled"],
        HCalCaloHitCollections = ["HcalBarrelCollectionRecKilled", "HcalEndcapCollectionRecKilled"],
        RelCaloHitCollections = [
            "EcalBarrelRelationsSimRec", "EcalEndcapRelationsSimRec",
            "HcalBarrelRelationsSimRec", "HcalEndcapRelationsSimRec",
            "MuonBarrelHitsRelations", "MuonEndcapHitsRelations"],
        PFOCollectionName = ["PandoraPFOs"],
        StartVertexCollectionName = ["PandoraStartVertices"],
        OutputLevel = INFO
    )